// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readNMDxmlCpp
Rcpp::List readNMDxmlCpp(Rcpp::CharacterVector inputFile, Rcpp::List xsdObjects);
RcppExport SEXP _RNMDAPI_readNMDxmlCpp(SEXP inputFileSEXP, SEXP xsdObjectsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< Rcpp::CharacterVector >::type inputFile(inputFileSEXP);
    Rcpp::traits::input_parameter< Rcpp::List >::type xsdObjects(xsdObjectsSEXP);
    rcpp_result_gen = Rcpp::wrap(readNMDxmlCpp(inputFile, xsdObjects));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RNMDAPI_readNMDxmlCpp", (DL_FUNC) &_RNMDAPI_readNMDxmlCpp, 2},
    {NULL, NULL, 0}
};

RcppExport void R_init_RNMDAPI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
