// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// readBioticXMLCpp
List readBioticXMLCpp(CharacterVector inputFile, List keys, NumericVector dim);
RcppExport SEXP _RNMDAPI_readBioticXMLCpp(SEXP inputFileSEXP, SEXP keysSEXP, SEXP dimSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< CharacterVector >::type inputFile(inputFileSEXP);
    Rcpp::traits::input_parameter< List >::type keys(keysSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type dim(dimSEXP);
    rcpp_result_gen = Rcpp::wrap(readBioticXMLCpp(inputFile, keys, dim));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_RNMDAPI_readBioticXMLCpp", (DL_FUNC) &_RNMDAPI_readBioticXMLCpp, 3},
    {NULL, NULL, 0}
};

RcppExport void R_init_RNMDAPI(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
