# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

readNMDxmlCpp <- function(inputFile, xsdObjects) {
    .Call('_RNMDAPI_readNMDxmlCpp', PACKAGE = 'RNMDAPI', inputFile, xsdObjects)
}

readNMDxmlCppStream <- function(inputFile, xsdObjects) {
    .Call('_RNMDAPI_readNMDxmlCppStream', PACKAGE = 'RNMDAPI', inputFile, xsdObjects)
}

